version: '3.8'

services:
  db:
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db

# db:
#   image: postgres:13
#   restart: always
#   environment:
#     POSTGRES_PASSWORD: password
#     POSTGRES_USER: user
#     POSTGRES_DB: db
#   ports:
#     - 5432:5432
#   volumes:
#     - ./data:/var/lib/postgresql/data

# adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 8080:8080

# app:
#   build: .
#   command: bash -c "python manage.py migrate && python manage.py runserver
