version: '3.8'

services:

  app:
    build: .
    ports:
      - 3000:3000
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db
